export const providersData = [
    {
        id: 'p1',
        name: "Wash & Fold Pro",
        image: "WFP",
        address: "Shop No 12, Sai Durga Complex, Beside D-Mart, Madhapur, Hyderabad, Telangana - 500081",
        contactNumber: "+91 98765 43210",
        operatingHours: "9:00 AM – 8:00 PM (All Days)",
        serviceArea: ["Madhapur", "Jubilee Hills", "Gachibowli", "HITEC City"],
        turnaroundTime: "24–48 hrs",
        rating: 4.8,
        pricePerKg: 80,
        serviceRates: { "WashFold": 80, "WashIron": 110, "Iron": 60 },
        services: ["WashFold", "WashIron", "Iron"],
        about: "Top rated laundry service with eco-friendly products and next-day delivery."
    },
    {
        id: 'p1b',
        name: "Crystal Clean Laundry",
        image: "CCL",
        address: "Ground Floor, Metro Plaza, Jubilee Hills, Hyderabad, Telangana - 500033",
        contactNumber: "+91 98123 45678",
        operatingHours: "8:00 AM – 9:00 PM (Mon-Sat)",
        serviceArea: ["Jubilee Hills", "Banjara Hills", "Film Nagar", "Madhapur"],
        turnaroundTime: "18–32 hrs",
        rating: 4.6,
        pricePerKg: 90,
        serviceRates: { "WashFold": 90, "WashIron": 120, "Iron": 65 },
        services: ["WashFold", "WashIron", "Iron", "DryClean"],
        about: "Premium care for your garments with fast turnaround."
    },
    {
        id: 'p2',
        name: "Quick Cleaners",
        image: "QC",
        address: "Shop No 4, Sector 15 Market, Near Nirula's, Noida, Uttar Pradesh - 201301",
        contactNumber: "+91 97654 32109",
        operatingHours: "9:30 AM – 8:30 PM (All Days)",
        serviceArea: ["Sector 15", "Sector 16", "Sector 18", "Atta Market"],
        turnaroundTime: "16–24 hrs",
        rating: 4.5,
        pricePerKg: 75,
        serviceRates: { "WashFold": 75, "WashIron": 105, "Iron": 55 },
        services: ["WashFold", "DryClean"],
        about: "Fast and reliable everyday laundry service."
    },
    {
        id: 'p2b',
        name: "Noida Wash House",
        image: "NWH",
        address: "Unit 2, City Center Mall Basement, Sector 32, Noida, Uttar Pradesh - 201307",
        contactNumber: "+91 96543 21098",
        operatingHours: "10:00 AM – 8:00 PM (All Days)",
        serviceArea: ["Sector 32", "Sector 34", "Sector 50", "Sector 62"],
        turnaroundTime: "24–36 hrs",
        rating: 4.7,
        pricePerKg: 70,
        serviceRates: { "WashFold": 70, "WashIron": 100, "Iron": 50 },
        services: ["WashFold", "WashIron", "Iron"],
        about: "Affordable and spotless cleaning for your daily wear."
    },
    {
        id: 'p3',
        name: "Iron Master",
        image: "IM",
        address: "Shop 45, 2nd Cross, MC Road, Near Vijayanagar Metro Station, Bengaluru, Karnataka - 560040",
        contactNumber: "+91 95432 10987",
        operatingHours: "8:30 AM – 9:00 PM (All Days)",
        serviceArea: ["Vijayanagar", "Rajajinagar", "Basaveshwaranagar", "Chord Road"],
        turnaroundTime: "12–24 hrs",
        rating: 4.9,
        pricePerKg: 60,
        serviceRates: { "WashFold": 80, "WashIron": 110, "Iron": 60 },
        services: ["Iron"],
        about: "Specialists in crisp, professional ironing for all your garments."
    },
    {
        id: 'p3b',
        name: "EcoWash",
        image: "EW",
        address: "Store 3, Green Park Avenue, Indiranagar, Bengaluru, Karnataka - 560038",
        contactNumber: "+91 94321 09876",
        operatingHours: "9:00 AM – 8:00 PM (All Days)",
        serviceArea: ["Indiranagar", "Domlur", "Koramangala", "HAL 2nd Stage"],
        turnaroundTime: "24–48 hrs",
        rating: 4.8,
        pricePerKg: 85,
        serviceRates: { "WashFold": 85, "WashIron": 115, "Iron": 60 },
        services: ["WashFold", "WashIron", "DryClean"],
        about: "100% organic detergents and energy-efficient washing."
    }
];
